In [5]:
import pandas as pd
import matplotlib.pyplot as plt
porto1_df=pd.read_csv('porto1.csv')
porto1_df

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,ps_ind_13_bin,ps_ind_14,ps_ind_15,ps_ind_16_bin,ps_ind_17_bin
0,7,0,2,2,5,1,0,0,1,0,0,0,0,0,0,0,11,0,1
1,9,0,1,1,7,0,0,0,0,1,0,0,0,0,0,0,3,0,0
2,13,0,5,4,9,1,0,0,0,1,0,0,0,0,0,0,12,1,0
3,16,0,0,1,2,0,0,1,0,0,0,0,0,0,0,0,8,1,0
4,17,0,0,2,0,1,0,1,0,0,0,0,0,0,0,0,9,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51770,129813,0,0,1,4,0,0,1,0,0,0,0,0,0,0,0,3,0,0
51771,129814,0,2,2,3,0,0,0,0,1,0,0,0,0,0,0,12,1,0
51772,129815,0,4,1,3,1,0,0,1,0,0,0,0,0,0,0,0,1,0
51773,129816,0,5,1,3,1,0,0,1,0,0,0,0,0,0,0,3,0,1
51774,129818,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,11,1,0

In [6]:
import numpy as np
porto1_df.replace(-1,np.NaN,inplace=True)
porto1_df.isnull().sum()

id                 0
target             0
ps_ind_01          0
ps_ind_02_cat     14
ps_ind_03          0
ps_ind_04_cat      7
ps_ind_05_cat    476
ps_ind_06_bin      0
ps_ind_07_bin      0
ps_ind_08_bin      0
ps_ind_09_bin      0
ps_ind_10_bin      0
ps_ind_11_bin      0
ps_ind_12_bin      0
ps_ind_13_bin      0
ps_ind_14          0
ps_ind_15          0
ps_ind_16_bin      0
ps_ind_17_bin      0
dtype: int64

In [7]:
missing_value_percentage_df=pd.DataFrame({'Column_Name':porto1_df.columns,
                                          'Missing_value_count':porto1_df.isnull().sum(),
                                          'Missing_value_percentage':porto1_df.isnull().sum()/porto1_df.shape[0]*100})

missing_value_percentage_df=missing_value_percentage_df.sort_values(by='Missing_value_percentage',ascending=False)
missing_value_percentage_df

                 Column_Name  Missing_value_count  Missing_value_percentage
ps_ind_05_cat  ps_ind_05_cat                  476                  0.919363
ps_ind_02_cat  ps_ind_02_cat                   14                  0.027040
ps_ind_04_cat  ps_ind_04_cat                    7                  0.013520
id                        id                    0                  0.000000
ps_ind_10_bin  ps_ind_10_bin                    0                  0.000000
ps_ind_16_bin  ps_ind_16_bin                    0                  0.000000
ps_ind_15          ps_ind_15                    0                  0.000000
ps_ind_14          ps_ind_14                    0                  0.000000
ps_ind_13_bin  ps_ind_13_bin                    0                  0.000000
ps_ind_12_bin  ps_ind_12_bin                    0                  0.000000
ps_ind_11_bin  ps_ind_11_bin                    0                  0.000000
ps_ind_08_bin  ps_ind_08_bin                    0                  0.000000
ps_ind_09_bin  ps_ind_09_bin                    0                  0.000000
target                target                    0                  0.000000
ps_ind_07_bin  ps_ind_07_bin                    0                  0.000000
ps_ind_06_bin  ps_ind_06_bin                    0                  0.000000
ps_ind_03          ps_ind_03                    0                  0.000000
ps_ind_01          ps_ind_01                    0                  0.000000
ps_ind_17_bin  ps_ind_17_bin                    0                  0.000000

In [8]:
cols_to_drop=[]

cols_with_missing_values_grt_50=list(missing_value_percentage_df[missing_value_percentage_df['Missing_value_percentage']>50].index)

for col in porto1_df.columns:
    if porto1_df[col].nunique()==porto1_df.shape[0] or porto1_df[col].nunique()==1:
        cols_to_drop.append(col)
        

columns_to_drop=cols_to_drop+cols_with_missing_values_grt_50

porto1_df.drop(columns=columns_to_drop,inplace=True)

In [9]:
for col in porto1_df:
    if col!='ps_ind_05_cat':
        porto1_df[col]=porto1_df[col].astype(object)
        
porto1_df['ps_ind_05_cat'].dtype

dtype('float64')

In [10]:
for col in porto1_df:
    if col!='ps_ind_04_cat':
        porto1_df[col]=porto1_df[col].astype(object)
        
porto1_df['ps_ind_04_cat'].dtype

dtype('O')

In [11]:
for col in porto1_df:
    if col!='ps_ind_02_cat':
        porto1_df[col]=porto1_df[col].astype(object)
        
porto1_df['ps_ind_02_cat'].dtype

dtype('O')

AttributeError: 'float' object has no attribute 'fillna'

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test=train_test_split(porto1_df,test_size=0.2,random_state=50)

for col in X_train.columns:
    if X_train[col].dtype=='object':
        X_train[col]=X_train[col].fillna(X_train[col].mode()[0]).astype(object)
        X_test[col]=X_test[col].fillna(X_train[col].mode()[0]).astype(object)
        
    else:
        X_train[col]=X_train[col].fillna(X_train[col].mean())
        X_test[col]=X_test[col].fillna(X_train[col].mean())

C:\Users\my laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\my laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [13]:
from sklearn.preprocessing import LabelEncoder
import numpy as np


class LabelEncoderExt(object):
    def __init__(self):
        self.label_encoder = LabelEncoder()
        
    def fit(self, data_list):
        self.label_encoder = self.label_encoder.fit(list(data_list) + ['Unknown'])
        self.classes_ = self.label_encoder.classes_

        return self
    def transform(self, data_list):
        new_data_list = list(data_list)
        for unique_item in np.unique(data_list):
            if unique_item not in self.label_encoder.classes_:
                new_data_list = ['Unknown' if x==unique_item else x for x in new_data_list]

        return self.label_encoder.transform(new_data_list)

In [14]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoderExt()

for col in X_train.columns:
    if X_train[col].dtype=='object':
        le.fit(X_train[col])
        X_train[col]=le.transform(X_train[col])
        X_test[col]=le.transform(X_test[col])

C:\Users\my laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
C:\Users\my laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\my laptop\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [15]:
for col in porto1_df:
    if X_train[col].dtype=='object':
        X_train[col]=le.fit.transform(X_train[col])
    if X_train[col].dtype=='int64'or 'float64':
        print('no')

no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no
no

In [93]:
!pip install imblearn

Requirement already satisfied: imblearn in c:\users\my laptop\anaconda3\lib\site-packages (0.0)
Requirement already satisfied: imbalanced-learn in c:\users\my laptop\anaconda3\lib\site-packages (from imblearn) (0.6.1)
Requirement already satisfied: scikit-learn>=0.22 in c:\users\my laptop\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (0.22.1)
Requirement already satisfied: scipy>=0.17 in c:\users\my laptop\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.3.1)
Requirement already satisfied: joblib>=0.11 in c:\users\my laptop\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (0.13.2)
Requirement already satisfied: numpy>=1.11 in c:\users\my laptop\anaconda3\lib\site-packages (from imbalanced-learn->imblearn) (1.16.5)

In [22]:
from sklearn.model_selection import train_test_split

X_train,X_test=train_test_split(porto1_df,test_size=0.2,random_state=50)

import imblearn
from imblearn.over_sampling import SMOTE

smote=SMOTE(sampling_strategy=0.40)
Xsmote,Ysmote=smote.fit_resample(X_train,Y_train)

X_train.shape

NameError: name 'Y_train' is not defined