In [26]:
import pandas as pd
import matplotlib.pyplot as plt
Mercedes_df=pd.read_csv('Mercedes.csv')
Mercedes_df

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [15]:
Mercedes_df.shape
Mercedes_df.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [16]:
Mercedes_df.columns.isnull().sum()

0

In [30]:
missing_value_percentage_df=pd.DataFrame({'Column_Name':Mercedes_df.columns,
                                          'Missing_value_count':Mercedes_df.isnull().sum(),
                                          'Missing_value_percentage':Mercedes_df.isnull().sum()/Mercedes_df.shape[0]*100})

missing_value_percentage_df=missing_value_percentage_df.sort_values(by='Missing_value_percentage',ascending=False)
missing_value_percentage_df

     Column_Name  Missing_value_count  Missing_value_percentage
ID            ID                    0                       0.0
X254        X254                    0                       0.0
X263        X263                    0                       0.0
X262        X262                    0                       0.0
X261        X261                    0                       0.0
...          ...                  ...                       ...
X127        X127                    0                       0.0
X126        X126                    0                       0.0
X125        X125                    0                       0.0
X124        X124                    0                       0.0
X385        X385                    0                       0.0

[378 rows x 3 columns]

In [52]:
cols_to_drop=[]
#cols_with_missing_values_greatthn_50=list(missing_value_percentage_df[missing_value_percentage_df['missing_value_percentage_df']>50].index)

for cols in Mercedes_df.columns:
     if Mercedes_df[col].nunique()==Mercedes_df.shape[0] or Mercedes_df[col].nunique()==1:
        cols_to_drop.append(cols)
columns_to_drop=cols_to_drop
Mercedes_df.drop(columns=columns_to_drop,inplace=True)
Mercedes_df.drop

<bound method DataFrame.drop of         ID       y  X0 X1  X2 X3 X4  X5 X6 X8  ... X375 X376 X377 X378 X379  \
0        0  130.81   k  v  at  a  d   u  j  o  ...    0    0    1    0    0
1        6   88.53   k  t  av  e  d   y  l  o  ...    1    0    0    0    0
2        7   76.26  az  w   n  c  d   x  j  x  ...    0    0    0    0    0
3        9   80.62  az  t   n  f  d   x  l  e  ...    0    0    0    0    0
4       13   78.02  az  v   n  f  d   h  d  n  ...    0    0    0    0    0
...    ...     ...  .. ..  .. .. ..  .. .. ..  ...  ...  ...  ...  ...  ...
4204  8405  107.39  ak  s  as  c  d  aa  d  q  ...    1    0    0    0    0
4205  8406  108.77   j  o   t  d  d  aa  h  h  ...    0    1    0    0    0
4206  8412  109.22  ak  v   r  a  d  aa  g  e  ...    0    0    1    0    0
4207  8415   87.48  al  r   e  f  d  aa  l  u  ...    0    0    0    0    0
4208  8417  110.85   z  r  ae  c  d  aa  g  w  ...    1    0    0    0    0

     X380 X382 X383 X384 X385
0       0    0    0    0    0
1       0    0    0    0    0
2       0    1    0    0    0
3       0    0    0    0    0
4       0    0    0    0    0
...   ...  ...  ...  ...  ...
4204    0    0    0    0    0
4205    0    0    0    0    0
4206    0    0    0    0    0
4207    0    0    0    0    0
4208    0    0    0    0    0

[4209 rows x 378 columns]>

In [57]:
for col in Mercedes_df.columns:
    if col!='ID':
        Mercedes_df[col]=Mercedes_df[col].astype(object)
        
Mercedes_df['ID'].dtype

dtype('O')

In [91]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(Mercedes_df,y,test_size=0.2,random_state=43)

NameError: name 'y' is not defined

In [80]:
from sklearn.preprocessing import LabelEncoder
import numpy as np


class LabelEncoderExt(object):
    def __init__(self):
        self.label_encoder = LabelEncoder()
    
    def fit(self, data_list):
        self.label_encoder = self.label_encoder.fit(list(data_list) + ['Unknown'])
        self.classes_ = self.label_encoder.classes_
        return self
    def transform(self, data_list):
        new_data_list = list(data_list)
        for unique_item in np.unique(data_list):
            if unique_item not in self.label_encoder.classes_:
                new_data_list = ['Unknown' if x==unique_item else x for x in new_data_list]

        return self.label_encoder.transform(new_data_list)

In [85]:
from sklearn.decomposition import PCA
pca=PCA()
X_train_pca_df=pd.DataFrame(pca.fit_transform(X_train))

X_train_pca_df

pca.explained_variance_ratio_

plt.plot(np.cumsum(pca.explained_variance_ratio_))

plt.xlabel('Number of Principal Components')
plt.ylabel('Explained Variance ratio')

ValueError: could not convert string to float: 'at'

In [88]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

vif_pca= pd.DataFrame()
vif_pca['VIF Factor_PCA']= [variance_inflation_factor(X_train_pca_df.values,i) for i in range(X_train_pca_df.shape[1])]

vif_pca['Column Name']= X_train_pca_df.columns
vif_pca

NameError: name 'X_train_pca_df' is not defined